[package]
name = "cli-template"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
clap = "2.33.3"
solana-clap-utils = "=1.8.1"
solana-cli-config = "=1.8.1"
solana-client = "=1.8.1"
solana-logger = "=1.8.1"
solana-remote-wallet = "=1.8.1"
solana-sdk = "=1.8.1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
solana-validator = "=1.8.1"

[workspace]
